version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - net
    restart: always
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_CLIENT_PORT}:${DB_CLIENT_PORT}"
    networks:
      - net
    depends_on:
      - mongo

  golang-api:
    container_name: golang-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./server.log:/app
      - ./.env:/build/.env
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  mongodb_data: