version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_CLIENT_PORT}:${DB_CLIENT_PORT}"
    networks:
      - mongo-network
    depends_on:
      - mongo

networks:
  mongo-network:

volumes:
  mongodb_data:
#    networks:
#      - net

#  golang-api:
#    container_name: golang-app
#    build:
#      dockerfile: Dockerfile
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    networks:
#      - net
