apiServer:
  host: golang-app
  port: 8000
  readTimeout: 5 # second
  writeTimeout: 10 # second

proxyServer:
  host: golang-app
  port: 8080
  readTimeout: 5 # second
  writeTimeout: 10 # second

logfile:
  path: server.log

mongodb:
  url: mongodb://mongodb:27017
  dbname: httpDb
  colrequest: request
  colresponse: response

certificateinfo:
  key:  certs/ca.key
  cert: certs/ca.crt
  subject: yngwie customproxy CA

shutdownTimeout: 10 # second
